version: "3"

services:
  assetfinder:
    build: assetfinder
    volumes:
      - "./input:/tools/input"
      - "./output:/tools/output"
       
  amass:
    build: amass
    volumes:
      - "./input:/tools/input"
      - "./output:/tools/output"
    
#  subfinder:
#    image: 'ice3man/subfinder'
#    volumes:
#      - ./input:/tools/input
    
  findomain:
    build: findomain
    volumes:
      - "./input:/tools/input"
      - "./output:/tools/output"

