version: "3"

services:
  assetfinder:
    build: assetfinder
    volumes:
      - "./input:/tools/input"
      - "./output:/tools/output"
       
  amass:
    build: amass
    volumes:
      - "./input:/tools/input"
      - "./output:/tools/output"
    
  subfinder:
    build: subfinder
    volumes:
      - "./input:/tools/input"
      - "./output:/tools/output"
    
  findomain:
   build: findomain
   volumes:
      - "./input:/tools/input"
      - "./output:/tools/output"

